### ISSUE TITLE
Mean disappears temporarily on Sampling screen histogram

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/projectile-data-lab#79] opened 2024-01-12 20:18 UTC
When I was launching a single sample on the Sampling screen, I noticed the mean dot on the histogram temporarily disappeared. It came back during another single sample's launch, but was on the histogram, disappears upon launch of a new sample, then reappeared (for n = 15) when the 3rd or 4th projectile landed. 

The timing for when the mean dot comes back on the histogram varies per sample size. Video below for n = 15 (mean dot is there when video starts, and right before the video hits the 1 second mark, the dot disappears).

https://github.com/phetsims/projectile-data-lab/assets/109630002/b9bf9ccf-744e-4b4c-b60c-4c30d035f432

**Comment by samreid** [comment] 2024-01-22 17:08
When we start creating sample 8, sample 8 becomes selected and displayed.  Would it be odd to select sample 7 in the histogram and select sample 8 in the field and selector panel?

**Comment by catherinecarter** [comment] 2024-01-22 17:29
I don't think I understand what you're describing, @samreid. Can you clarify?

**Comment by samreid** [comment] 2024-01-23 19:58
I labeled for meeting:design to remind us to discuss during one of our morning standups with @matthew-blackman @catherinecarter and me.

**Comment by samreid** [comment] 2024-01-24 16:29
The problem is about the block, not about the dot. It's OK for the dot to disappear when the field selects a new sample. So @matthew-blackman and I will fix the missing block.

**Comment by matthew-blackman** [comment] 2024-01-24 16:29
We noticed that the block reappears at the moment the last projectile is launched in the most recent sample.

**Comment by samreid** [comment] 2024-01-29 16:51
This is most likely related to #76

**Comment by samreid** [comment] 2024-01-29 23:44
The problem is that: we switch to `showingAirborneProjectiles` before we create any airborne projectiles but the updateComputedProperties thinks they are created at the same time.

This patch fixes the bug but is confusing

<details>

```diff

Subject: [PATCH] Switch to selectedSampleNumber instead of selectedSampleIndex, see https://github.com/phetsims/projectile-data-lab/issues/76
---
Index: js/sampling/model/SamplingField.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/sampling/model/SamplingField.ts b/js/sampling/model/SamplingField.ts
--- a/js/sampling/model/SamplingField.ts	(revision b8ec245922cd635866b4ff54def4a9f9556f6ec3)
+++ b/js/sampling/model/SamplingField.ts	(date 1706571747152)
@@ -191,6 +191,17 @@
 
     this.numberOfCompletedSamplesProperty.value = Math.max( 0, numberOfCompletedSamples );
 
+    if ( this.numberOfCompletedSamplesProperty.value === this.numberOfStartedSamplesProperty.value - 2 ) {
+      this.numberOfCompletedSamplesProperty.value = this.numberOfStartedSamplesProperty.value - 1;
+    }
+    console.log( '-----' );
+    console.log( 'number of started samples', this.numberOfStartedSamplesProperty.value );
+    console.log( 'number of completed samples', this.numberOfCompletedSamplesProperty.value );
+    console.log( '-----' );
+    // if ( this.numberOfCompletedSamplesProperty.value === 0 ) {
+    //   debugger;
+    // }
+
     // Update the sample mean
     const projectilesInSelectedSample = this.getProjectilesInSelectedSample();
 

```

</details>

**Comment by samreid** [comment] 2024-01-30 01:48
OK I fixed the implementation in `updateComputedProperties` and it fixed the disappearing block problem.  I think this is ready for review.

**Comment by matthew-blackman** [comment] 2024-01-30 20:04
The commits have been reviewed and everything is working great. Added a line on documentation to explain the order of Property updates in SamplingModel. Closing.

**Closed by matthew-blackman** 2024-01-30 20:04 UTC
Labels: type:bug, status:ready-for-review
