### ISSUE TITLE
[CODAP] Putting variables side by side is buggy

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/projectile-data-lab#358] opened 2024-10-22 00:53 UTC
**Test device**
MacBook Air M1 chip

**Operating System**
15.0.1

**Browser**
Safari 18.0.1 and Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/1157, I am having difficulty creating a table where 2 variables are side-by-side in the hierarchy. Sometimes, when I open CODAP everything works perfectly in both safari and chrome. Other times it doesn't work at all. I don't know why. Maybe it's just me.....

**Steps to reproduce**
I was having issues with all variables, but here are some example steps:
1.   Have all variables checked 
2.  On the Variables screen, create some data changing the launcher, launch angle and projectile. 
3. In the table, pull the launch orientation column all the way to the left to create a hierarchy
4. Grab and try to place the launcher column or projectile column next to the launch angle

**Visuals**
sorry this video is really long but I wanted to show how sometimes it works and sometimes it doesn't....

https://github.com/user-attachments/assets/bd05e100-9c24-4cc3-8301-139c93d85422

**Comment by KatieWoe** [comment] 2024-10-22 18:57
I had one or two failed drags on Win 11 Chrome from the pulled out table back to the main table, so I don't think it's mac specific.

**Comment by Matthew-Moore240** [comment] 2024-10-22 19:06
Seeing this same behavior on Chromebook as well.

**Comment by samreid** [comment] 2024-11-08 02:53
I don't believe we have control over this part of the CODAP UI. If I recall correctly, there was discussion that this kind of bug may be addressed in a future version of CODAP.

**Comment by samreid** [comment] 2024-11-11 21:06
@matthew-blackman confirmed this is a CODAP issue we have run into since day 1. CODAP team is aware of it. There is an issue for it. Therefore, closing as will-not-fix.

**Closed by samreid** 2024-11-11 21:06 UTC
Labels: type:bug
