### ISSUE TITLE
Differentiate projectile sounds based on type

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#133] opened 2024-02-06 23:16 UTC
In the 2/6 PDL Sound Design meeting, it was discussed that we want to try a subtle differentiation of projectile landing sound for cannonballs, pumpkins and pianos. @Ashton-Morris is going to mock up some options.

**Comment by samreid** [comment] 2024-02-08 02:27
Duplicate of 140, closing.

**Closed by samreid** 2024-02-08 02:27 UTC
Labels: design:sound, meeting:sonification
