### ISSUE TITLE
Field Sign Data Navigator not working on Screen 4

### ISSUE THREAD

**Issue by terracoda** [phetsims/projectile-data-lab#247] opened 2024-03-12 18:56 UTC
![Screenshot 2024-03-12 at 16 23 35](https://github.com/phetsims/projectile-data-lab/assets/1902116/9f8f5f7e-3adf-4a09-95ae-b54b247a199b)

If I can't navigate this data, I am wondering if the navigator representation and tab stop should be removed?

**Comment by matthew-blackman** [comment] 2024-03-12 22:15
It appears to be working correctly in my testing. On the Sampling screen, the field sign is used to navigate between samples of multiple projectiles, not individual projectiles. If you click the launch button again after collecting a full sample, or use Continuous mode to collect multiple samples, you will be able to navigate between samples.

We recognize that this screen is significantly different from screens 1-3, and it addressed totally different learning goals. Hope this helps!

**Comment by matthew-blackman** [comment] 2024-03-13 17:23
@terracoda and I discussed this and confirmed that the Sampling screen is working as intended. Closing.

**Closed by matthew-blackman** 2024-03-13 17:23 UTC
Labels: type:question, design:alt-input, design:general
