### ISSUE TITLE
Designs of Mystery Launchers 5-6 can fail to render after a period of time

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/projectile-data-lab#271] opened 2024-03-22 15:23 UTC
**Test device**
iPad 9th generation

**Operating System**
iPadOS 17.3

**Browser**
Safari 

**Problem description**
For https://github.com/phetsims/qa/issues/1060, after playing with the sim for a while, Mystery Launchers 5 and 6 appeared as gray and black instead of with their designs. Restarting the sim didn't fix the problem; only clearing my cache did. This happened 2 times on the iPad and once with mac/safari during testing. 

**Visuals**
<img width="328" alt="Screenshot 2024-03-22 at 11 21 06 AM" src="https://github.com/phetsims/projectile-data-lab/assets/87318828/d07aa3f5-caa7-4455-a50e-560b6925c26d">
<img width="334" alt="Screenshot 2024-03-22 at 11 20 40 AM" src="https://github.com/phetsims/projectile-data-lab/assets/87318828/5712fb64-5d04-44d3-8c1e-855b89782abc">
<img width="334" alt="Screenshot 2024-03-22 at 11 20 04 AM" src="https://github.com/phetsims/projectile-data-lab/assets/87318828/0c2b7e3b-cd5f-4d2a-9ab0-ffd0960a4e9c">

**Comment by matthew-blackman** [comment] 2024-04-01 19:16
@samreid and I are unable to reproduce this with Safari on macOS. 

@Nancy-Salpepi how long does this take to trigger this? Is there a direction that we can pursue to try and reproduce it reliably?

@jonathanolson we are also wondering if this looks like something you are aware of. We are using svgs for the launcher pattern, but there is no difference in the way that launchers 5 and 6 are being rendered compared to the other launchers. Is there something we can pursue further to try and track down the source of this rendering issue?

**Comment by Nancy-Salpepi** [comment] 2024-04-01 19:21
I wish I had more info to give. I will go back and take another look on the iPad because I spent less time testing on that device and it happened twice there.

**Comment by Nancy-Salpepi** [comment] 2024-04-01 20:45
I looked back at the dev version and the easiest way to reproduce it on the iPad/mac + safari is to keep changing the query parameters. 

For example, with mac + safari:
1. Clear cache
2. Open Variability screen of sim --all looks good
3. Add ?autoGenerateData=true to url
4. Check Launchers 5-6 on Variability screen
5. Change to ?autoGenerateData=false
6. Check Launchers
7. keep repeating

I also saw it with iPad by changing between stringTests. I hope this helps!


https://github.com/phetsims/projectile-data-lab/assets/87318828/dc4cda7d-f331-4528-81f0-6d5fc3336e3c

**Comment by samreid** [comment] 2024-04-01 22:05
I saw the problem by following @Nancy-Salpepi instructions and it happened after setting auto generate to false only one time, on the built dev version:

<img width="348" alt="image" src="https://github.com/phetsims/projectile-data-lab/assets/679486/d7b10945-caa7-4d6e-a6e5-b0ac0c417984">

Note it is only broken in the icon and not in the play area.

**Comment by samreid** [comment] 2024-04-01 22:12
I was surprised to see that removing the rasterization did not help here. The icons are rendered in https://github.com/phetsims/projectile-data-lab/blob/main/js/common/view/MysteryLauncherIcon.ts, and we are ready to request help from @jonathanolson

**Comment by Nancy-Salpepi** [comment] 2024-04-01 23:18
To get the Launcher in the play area solid gray/black:
1. On the Variability screen click on Launcher 5
2. Add ?stringTest=double
3. If the Launcher 5 icon is gray on the Variability screen, select it --the launcher should also be gray in the play area
4. If the Launcher 5 icon isn't gray, change the stringTest to something else until it is and then repeat step 3. 

Hope this helps!

**Comment by jonathanolson** [comment] 2024-04-03 20:06
Isolated to somewhat-minimal html: https://bayes.colorado.edu/dev/phettest/scenery/tests/browsers/safari-pattern-test.html

If loaded in Safari (in a new tab), it seems to randomly decide to show the texture or not.

**Comment by jonathanolson** [comment] 2024-04-03 20:07
It seems like rasterization actually might be required for this bug to present, but I haven't tested fully without rasterization.

**Comment by jonathanolson** [comment] 2024-04-03 20:08
Actual (Safari, sometimes) vs. Expected (Chrome)
<img width="375" alt="image" src="https://github.com/phetsims/projectile-data-lab/assets/480878/84b0c2d9-7911-4588-bf41-43cb3fe60b14">
<img width="383" alt="image" src="https://github.com/phetsims/projectile-data-lab/assets/480878/12fc4203-02a7-43c5-b2a1-c06cba785fbb">

**Comment by samreid** [comment] 2024-04-03 20:54
In https://github.com/phetsims/projectile-data-lab/issues/271#issuecomment-2030661414 I reported that removing rasterization from the icon did not seem to prevent the problem.

**Comment by jonathanolson** [comment] 2024-04-03 22:24
Added a workaround that forces a rasterization of the SVG launcher pattern (on Safari) synchronously to a Canvas pattern, so it isn't getting an embedded SVG-image inside SVG case (where the pattern seems to fail).

**Comment by jonathanolson** [comment] 2024-04-04 01:21
Let me know if this workaround works for people!

**Comment by samreid** [comment] 2024-04-05 17:46
@matthew-blackman and I had difficulty reproducing the problem again, even before the fix from @jonathanolson. I'll create a dev test for @Nancy-Salpepi to check a built version before RC.1.

**Comment by samreid** [comment] 2024-04-05 17:56
Deployed: https://phet-dev.colorado.edu/html/projectile-data-lab/1.0.0-dev.23/phet/projectile-data-lab_all_phet.html
Deployed: https://phet-dev.colorado.edu/html/projectile-data-lab/1.0.0-dev.23/phet-io/

**Comment by samreid** [comment] 2024-04-05 17:58
I tested the link above on macOS Safari, and saw this result after loading once with no query parameters:

https://phet-dev.colorado.edu/html/projectile-data-lab/1.0.0-dev.23/phet/projectile-data-lab_all_phet.html?autoGenerateData=true&stringTest=a

<img width="696" alt="image" src="https://github.com/phetsims/projectile-data-lab/assets/679486/79c974de-34a5-4b09-a499-173142ef95f5">

Do you think there is something odd in the SVG itself? Should we try exporting it a different way? Should we try a PNG instead of SVG? @jonathanolson what do you recommend?

**Comment by samreid** [comment] 2024-04-08 16:20
@jonathanolson suggested trying PNG to see if it works around the problem for now.

**Comment by matthew-blackman** [comment] 2024-04-09 17:23
@samreid and I made progress tracking down the source of this bug. It only affects the two svg files that are using the <pattern> tag (added to the file when Illustrator exports a 'pattern' image type.

It looks like Safari may not have liked the following part of the last 2 launcher svgs:
<pattern id="StarsYellow" x="0" y="0" width="75" height="75" patternTransform="translate(-10715.89 23009.05) rotate(45) scale(2.97)" patternUnits="userSpaceOnUse" viewBox="0 0 75 75">

The commit updates those 2 svgs to avoid using the pattern tag, and instead using all vector paths. @Nancy-Salpepi @samreid can you see if this fixes the problem?

**Comment by samreid** [comment] 2024-04-09 17:43
Everything looks good here (testing on unbuilt).

**Comment by samreid** [comment] 2024-04-09 18:02
I tested a local built version, and everything seems good. Closing.

**Closed by samreid** 2024-04-09 18:02 UTC
Labels: type:bug, dev:help-wanted
