### ISSUE TITLE
CT: sampleMeanProperty should not be null in showingCompleteSampleWithoutMean phase

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-data-lab#336] opened 2024-06-13 23:20 UTC
Occurring occassionally for both PDL and PSD:

```
projectile-data-lab : phet-io-state-fuzz : unbuilt
URL: http://128.138.93.172/continuous-testing/ct-snapshots/1718308251971/phet-io-wrappers/state/?sim=projectile-data-lab&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22projectile-data-lab%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1718308251971%22%2C%22timestamp%22%3A1718309728060%7D
ERROR: Assertion failed: sampleMeanProperty should not be null in showingCompleteSampleWithoutMean phase. Projectiles in selected sample: 2. Sample size: 2
STACK: Error: Assertion failed: sampleMeanProperty should not be null in showingCompleteSampleWithoutMean phase. Projectiles in selected sample: 2. Sample size: 2
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1718308251971/assert/js/assert.js:45:13)
    at assert (SamplingField.ts:184:18)
    at listener (TinyEmitter.ts:213:6)
    at notifyLoop (TinyEmitter.ts:196:13)
    at emit (Emitter.ts:64:21)
    at emit (PhetioStateEngine.ts:271:25)
    at setState (PhetioStateEngine.ts:282:9)
    at setFullState (phetioEngine.ts:1158:33)
    at apply (phetioCommandProcessor.ts:429:50)
    at process (phetioCommandProcessor.ts:303:35)
    at getReturn (phetioCommandProcessor.ts:311:17)
    at Array.map
    at map (phetioCommandProcessor.ts:301:29)
    at processCommands (phetioCommandProcessor.ts:242:34)
[URL] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1718308251971%2Fphet-io-wrappers%2Fstate%2F%3Fsim%3Dprojectile-data-lab%26locales%3D*%26phetioWrapperDebug%3Dtrue%26fuzz%26phetioDebug%3Dtrue&testInfo=%7B%22test%22%3A%5B%22projectile-data-lab%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1718308251971%22%2C%22timestamp%22%3A1718309728060%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1718308251971%2Fphet-io-wrappers%2Fstate%2F%3Fsim%3Dprojectile-data-lab%26locales%3D*%26phetioWrapperDebug%3Dtrue%26fuzz%26phetioDebug%3Dtrue&testInfo=%7B%22test%22%3A%5B%22projectile-data-lab%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1718308251971%22%2C%22timestamp%22%3A1718309728060%7D
[ATTACHED] 
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1718308251971/phet-io-wrappers/state/?sim=projectile-data-lab&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22projectile-data-lab%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1718308251971%22%2C%22timestamp%22%3A1718309728060%7D
[ATTACHED] 
[NAVIGATED] about:blank
[ATTACHED] 
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1718308251971/projectile-data-lab/projectile-data-lab_en.html?brand=phet-io&ea&postMessageOnError&sim=projectile-data-lab&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22projectile-data-lab%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1718308251971%22%2C%22timestamp%22%3A1718309728060%7D&frameTitle=source
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1718308251971/projectile-data-lab/projectile-data-lab_en.html?brand=phet-io&ea&postMessageOnError&sim=projectile-data-lab&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22projectile-data-lab%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1718308251971%22%2C%22timestamp%22%3A1718309728060%7D&frameTitle=destination
[CONSOLE] enabling assert
[CONSOLE] enabling assert
[CONSOLE] continuous-test-wrapper-load
[CONSOLE] continuous-test-wrapper-load
[CONSOLE] Assertion failed:  sampleMeanProperty should not be null in showingCompleteSampleWithoutMean phase. Projectiles in selected sample: 2. Sample size: 2
[CONSOLE] Debug info: {
  "seed": 0.052051134811236244,
  "currentScreenName": "SamplingScreen",
  "simTopLayer": [
    "BarrierRectangle",
    "PopupParentNode: PhetMenu"
  ]
}
[PAGE ERROR] Error: Error: Assertion failed: sampleMeanProperty should not be null in showingCompleteSampleWithoutMean phase. Projectiles in selected sample: 2. Sample size: 2
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1718308251971/assert/js/assert.js:45:13)
    at http://128.138.93.172/continuous-testing/ct-snapshots/1718308251971/chipper/dist/js/projectile-data-lab/js/sampling/model/SamplingField.js:138:19
    at TinyEmitter.notifyLoop (http://128.138.93.172/continuous-testing/ct-snapshots/1718308251971/chipper/dist/js/axon/js/TinyEmitter.js:176:7)
    at TinyEmitter.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1718308251971/chipper/dist/js/axon/js/TinyEmitter.js:161:14)
    at Emitter.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1718308251971/chipper/dist/js/axon/js/Emitter.js:52:22)
    at PhetioStateEngine.setState (http://128.138.93.172/continuous-testing/ct-snapshots/1718308251971/chipper/dist/js/phet-io/js/PhetioStateEngine.js:253:26)
    at PhetioStateEngine.setFullState (http://128.138.93.172/continuous-testing/ct-snapshots/1718308251971/chipper/dist/js/phet-io/js/PhetioStateEngine.js:264:10)
    at PhetioEngine.implementation (http://128.138.93.172/continuous-testing/ct-snapshots/1718308251971/chipper/dist/js/phet-io/js/phetioEngine.js:989:34)
    at PhetioCommandProcessor.process (http://128.138.93.172/continuous-testing/ct-snapshots/1718308251971/chipper/dist/js/phet-io/js/phetioCommandProcessor.js:312:51)
    at getReturn (http://128.138.93.172/continuous-testing/ct-snapshots/1718308251971/chipper/dist/js/phet-io/js/phetioCommandProcessor.js:181:29)
    at http://128.138.93.172/continuous-testing/ct-snapshots/1718308251971/chipper/dist/js/phet-io/js/phetioCommandProcessor.js:189:18
    at Array.map (<anonymous>)
    at PhetioCommandProcessor.processCommands (http://128.138.93.172/continuous-testing/ct-snapshots/1718308251971/chipper/dist/js/phet-io/js/phetioCommandProcessor.js:178:30)
    at http://128.138.93.172/continuous-testing/ct-snapshots/1718308251971/chipper/dist/js/phet-io/js/phetioCommandProcessor.js:125:35
[CONSOLE] continuous-test-wrapper-error
[CONSOLE] continuous-test-wrapper-error

id: "Bayes Node Puppeteer"
Snapshot from 6/13/2024, 1:50:51 PM
```

**Comment by samreid** [comment] 2024-06-19 16:52
@matthew-blackman and I tried to solve this on several occasions and it's unclear what is solving the problem or how to address it. Not planning to work on this during this iteration.

**Comment by matthew-blackman** [comment] 2024-08-20 15:26
This is a duplicate of #329, closing.

**Closed by matthew-blackman** 2024-08-20 15:26 UTC
Labels: type:automated-testing
